title: Sushmita Behera # your name (or website title) here
logo: "/images/image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi!! I have been working as Catastrophe analyst in AIG from past 5 years. Gratuated in electronics & communication engineering and working in an insurance industry
  <br><br>
  Few interesting things about me, I have always been fascinated by the data and numbers. I started to grow interest in it once I started working closely with the data and
  findngs which have at times surprised me. I love to learn, I always push myself to keep on learning.
  <br><br>
  <a href="https://www.linkedin.com/in/sushmitabehera21/">View My LinkedIn Profile</a> 
  
