title: Sushmita Behera # your name (or website title) here
logo: "/images/image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi!! I have been working as Catastrophe analyst in AIG from past 5 years. Gratuated in electronics & communication engineering
  <br><br>
  Few interesting things about me
  <br><br>
  <a href="https://www.linkedin.com/in/sushmitabehera21/">View My LinkedIn Profile</a> 
  theme: jekyll-theme-minimal
 google_analytics: UA-000000-0 # your Google Analytics tracking ID here
